import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import APINavColumn from '@/components/APINavColumn'
import Main from '@/components/Main'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className=' grid grid-rows-[auto,1fr] h-screen '>
        <Header />
        <div className='flex h-full w-screen p-0 top-20 absolute'>
          {/* <div className='w-2/12 border-r-2 border-slate-300 flex flex-col p-8 h-full'> */}
          <APINavColumn />
          {/* </div> */}
          <Main>{children}</Main>
          {/* <div className='px-20 pt-8 w-10/12'>{children}</div> */}
        </div>
      </body>
    </html>
  )
}
