name: Integration Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    paths-ignore:
      - 'README.md'
jobs:
  ts-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm 8
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: 'pnpm'
      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile
      - name: Compile contracts
        run: pnpm hardhat compile
      - name: Run linter
        run: pnpm run lint
      - name: Run Prettier
        run: pnpm run prettier:check
      - name: Build package
        run: pnpm run build
      - name: Run helper func tests
        run: pnpm run test
      - name: Move into the wasm test app directory
        run: cd ./examples/wasm-test-app
      - name: Install dependencies and run wasm tests
        run: |
          cd ./examples/wasm-test-app
          pnpm install --no-frozen-lockfile
          NEXT_PUBLIC_REACT_APP_ENTRY_POINT=test pnpm run build
        env:
          CI: false
          NODE_ENV: development
