name: Integration Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
jobs:
  ts-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
      - name: Install npm dependencies
        run: npm install --frozen-lockfile
      - name: Compile contracts
        run: npx hardhat compile
      - name: Run linter
        run: npm run lint
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm run test