name: Integration Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    paths-ignore:
      - 'README.md'
jobs:
  ts-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile
      - name: Compile contracts
        run: pnpm hardhat compile
      - name: Run linter
        run: pnpm run lint
      - name: Build package
        run: pnpm run build
      - name: Run tests
        run: pnpm run test
